<div id="hero-search" class="container-fluid">
  <div class="container">
    <div class="left message">
      <h2>SEARCH RESULTS</h2>
      <h2>SEARCH RESULTS</h2>
      <h2>SEARCH RESULTS</h2>
      <h2>SEARCH RESULTS</h2>
    </div>
    <div id="center message">
      <h2>SEARCH RESULTS</h2>
      <h2>SEARCH RESULTS</h2>
      <h2>SEARCH RESULTS</h2>
      <h2>SEARCH RESULTS</h2>
    </div>
    <div class="right message">
      <h2>SEARCH RESULTS</h2>
      <h2>SEARCH RESULTS</h2>
      <h2>SEARCH RESULTS</h2>
      <h2>SEARCH RESULTS</h2>
    </div>
  </div>
</div>
