<ul class="nav nav-tabs" role="tablist">
  <li role="presentation" class="active">
    <a href="#all" aria-controls="home" role="tab" data-toggle="tab">
      All
    </a>
  </li>
  <li role="presentation">
    <a href="#home" aria-controls="profile" role="tab" data-toggle="tab">
      Home
    </a>
  </li>
  <li role="presentation">
    <a href="#blog" aria-controls="messages" role="tab" data-toggle="tab">
      Blog
    </a>
  </li>
  <li role="presentation">
    <a href="#shop" aria-controls="settings" role="tab" data-toggle="tab">
      Shop
    </a>
  </li>
  <li role="presentation">
    <a href="#portfolio" aria-controls="settings" role="tab" data-toggle="tab">
      Portfolio
    </a>
  </li>
  <li role="presentation">
    <a href="#pages" aria-controls="settings" role="tab" data-toggle="tab">
      Pages
    </a>
  </li>
  <li role="presentation">
    <a href="#component" aria-controls="settings" role="tab" data-toggle="tab">
      Components
    </a>
  </li>
</ul>
