<div class="tab-content">
  <div role="tabpanel" class="tab-pane active" id="all">
    <div class="row">
      <?php include('inc/homepage/tabs-block/tab-panel/00-home.inc'); ?>
      <?php include('inc/homepage/tabs-block/tab-panel/01-blog.inc'); ?>
      <?php include('inc/homepage/tabs-block/tab-panel/02-shop.inc'); ?>
      <?php include('inc/homepage/tabs-block/tab-panel/03-portfolio.inc'); ?>
      <?php include('inc/homepage/tabs-block/tab-panel/04-pages.inc'); ?>
      <?php include('inc/homepage/tabs-block/tab-panel/05-components.inc'); ?>
    </div>
  </div> 

  <div role="tabpanel" class="tab-pane" id="home">
    <div class="row">
      <?php include('inc/homepage/tabs-block/tab-panel/00-home.inc'); ?>
    </div>
  </div> 

  <div role="tabpanel" class="tab-pane" id="blog">
    <div class="row">
      <?php include('inc/homepage/tabs-block/tab-panel/01-blog.inc'); ?>
    </div>
  </div> 

  <div role="tabpanel" class="tab-pane" id="shop">
    <div class="row">
    <?php include('inc/homepage/tabs-block/tab-panel/02-shop.inc'); ?>
    </div>
  </div> 

  <div role="tabpanel" class="tab-pane" id="portfolio">
    <div class="row">
    <?php include('inc/homepage/tabs-block/tab-panel/03-portfolio.inc'); ?>
    </div>
  </div> 

  <div role="tabpanel" class="tab-pane" id="pages">
    <div class="row">
    <?php include('inc/homepage/tabs-block/tab-panel/04-pages.inc'); ?>
    </div>
  </div>

  <div role="tabpanel" class="tab-pane" id="components">
    <div class="row">
    <?php include('inc/homepage/tabs-block/tab-panel/05-components.inc'); ?>
    </div>
  </div>
</div>
