<div class="tab-content">
  <div role="tabpanel" class="tab-pane active" id="all">
    <?php include('inc/homepage/tabs-block/tab-panel/00-home.inc'); ?>
  </div> 

  <div role="tabpanel" class="tab-pane" id="home">
    <p>Home</p>
  </div> 

  <div role="tabpanel" class="tab-pane" id="blog">
    <p>Blog</p>
  </div> 

  <div role="tabpanel" class="tab-pane" id="shop">
    <p>Shop</p>
  </div> 

  <div role="tabpanel" class="tab-pane" id="portfolio">
    <p>Portfolio</p>
  </div> 

  <div role="tabpanel" class="tab-pane" id="pages">
    <p>Pages</p>
  </div> 

  <div role="tabpanel" class="tab-pane" id="components">
    <p>Componentes</p>
  </div>
</div>
