<div class="tab-content">
  <div role="tabpanel" class="tab-pane active" id="all">
    <?php include('inc/homepage/tabs-block/tab-panel/00-home.inc'); ?>
    <?php include('inc/homepage/tabs-block/tab-panel/01-blog.inc'); ?>
    <?php include('inc/homepage/tabs-block/tab-panel/02-shop.inc'); ?>
    <?php include('inc/homepage/tabs-block/tab-panel/03-portfolio.inc'); ?>
    <?php include('inc/homepage/tabs-block/tab-panel/04-pages.inc'); ?>
    
    
  </div> 

  <div role="tabpanel" class="tab-pane" id="home">
    <?php include('inc/homepage/tabs-block/tab-panel/00-home.inc'); ?>
  </div> 

  <div role="tabpanel" class="tab-pane" id="blog">
   <?php include('inc/homepage/tabs-block/tab-panel/01-blog.inc'); ?>
  </div> 

  <div role="tabpanel" class="tab-pane" id="shop">
    <?php include('inc/homepage/tabs-block/tab-panel/02-shop.inc'); ?>
  </div> 

  <div role="tabpanel" class="tab-pane" id="portfolio">
    <?php include('inc/homepage/tabs-block/tab-panel/03-portfolio.inc'); ?>
  </div> 

  <div role="tabpanel" class="tab-pane" id="pages">
    <?php include('inc/homepage/tabs-block/tab-panel/04-pages.inc'); ?>
  </div>

  <div role="tabpanel" class="tab-pane" id="components">
    <?php include('inc/homepage/tabs-block/tab-panel/05-components.inc'); ?>
  </div>
</div>
