<div id="tabs-block">
  <!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active"><a href="#all" aria-controls="home" role="tab" data-toggle="tab">All</a></li>
    <li role="presentation">
      <a href="#home" aria-controls="profile" role="tab" data-toggle="tab">
        Home
      </a>
    </li>
    <li role="presentation">
      <a href="#blog" aria-controls="messages" role="tab" data-toggle="tab">
        Blog
      </a>
    </li>
    <li role="presentation">
      <a href="#shop" aria-controls="settings" role="tab" data-toggle="tab">
        Shop
      </a>
    </li>
    <li role="presentation">
      <a href="#portfolio" aria-controls="settings" role="tab" data-toggle="tab">
        Portfolio
      </a>
    </li>
    <li role="presentation">
      <a href="#pages" aria-controls="settings" role="tab" data-toggle="tab">
        Pages
      </a>
    </li>
    <li role="presentation">
      <a href="#component" aria-controls="settings" role="tab" data-toggle="tab">
        Components
      </a>
    </li>
  </ul>
  <!-- Tab panes -->
  <div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="all">
      <div class="row">
        <div class="col-md-3 item">
          <img src="images/1.jpg" alt="1" width="550" height="420" class="img-responsive">
          <div class="caption">
            <p><strong>Starbis</strong></p>
          </div>
        </div> <!-- /.col-md-3 -->
        <div class="col-md-3 item">
          <img src="images/1.jpg" alt="1" width="550" height="420" class="img-responsive">
          <div class="caption">
            <p><strong>Starbis</strong></p>
          </div>
        </div> <!-- /.col-md-3 -->
        <div class="col-md-3 item">
          <img src="images/1.jpg" alt="1" width="550" height="420" class="img-responsive">
          <div class="caption">
            <p><strong>Starbis</strong></p>
          </div>
        </div> <!-- /.col-md-3 -->
        <div class="col-md-3 item">
          <img src="images/1.jpg" alt="1" width="550" height="420" class="img-responsive">
          <div class="caption">
            <p><strong>Starbis</strong></p>
          </div>
        </div> <!-- /.col-md-3 -->
      </div> <!-- /.row -->
    </div> <!-- /.tabpanel -->

    <div role="tabpanel" class="tab-pane" id="home">
      <p>Home</p>
    </div> <!-- /.tabpanel -->

    <div role="tabpanel" class="tab-pane" id="blog">
      <p>Blog</p>
    </div> <!-- /.tabpanel -->

    <div role="tabpanel" class="tab-pane" id="shop">
      <p>Shop</p>
    </div> <!-- /.tabpanel -->

    <div role="tabpanel" class="tab-pane" id="portfolio">
      <p>Portfolio</p>
    </div> <!-- /.tabpanel -->

    <div role="tabpanel" class="tab-pane" id="pages">
      <p>Pages</p>
    </div> <!-- /.tabpanel -->

    <div role="tabpanel" class="tab-pane" id="components">
      <p>Componentes</p>
    </div><!-- /.tabpanel -->
  </div> <!-- /.tab-content -->
</div> <!-- /#tabs-block -->
