<div id="tabs-block">
  <!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active"><a href="#home" aria-controls="home" role="tab" data-toggle="tab">Home</a></li>
    <li role="presentation"><a href="#profile" aria-controls="profile" role="tab" data-toggle="tab">Profile</a></li>
    <li role="presentation"><a href="#messages" aria-controls="messages" role="tab" data-toggle="tab">Messages</a></li>
    <li role="presentation"><a href="#settings" aria-controls="settings" role="tab" data-toggle="tab">Settings</a></li>
  </ul>

  <!-- Tab panes -->
  <div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="home"><img src="/images/1.jpeg" class="img-fluid"></div>
    <div role="tabpanel" class="tab-pane" id="profile"><img src="/images/2.jpg" class="img-fluid"></div>
    <div role="tabpanel" class="tab-pane" id="messages"><img src="/images/3.jpeg" class="img-fluid"></div>
    <div role="tabpanel" class="tab-pane" id="settings"><img src="/images/1524913221_572475_1524913364_noticia_normal.jpg" alt="1524913221_572475_1524913364_noticia_normal" width="1200" height="675">
    </div>
  </div>
</div>