<div id="hero">
  <div class="slide">
    <div class="container">
      <div class="row">
        <div class="col">
          <div class = "cycle-slideshow" 
            ciclo de datos-fx = scrollHorz
            data-cycle-timeout = 0>
            <! - anterior / siguiente enlaces ->
            <div class = "cycle-prev"> </div> 
            <div class = "cycle-next"> </div>
            <img src = "/images/home-slider-1-slide-1.jpg">
            <img src = "/images/home-slider-1-slide-2.jpg">
            <img src = "/images/home-slider-1-slide-3.jpg">
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
