<div id="hero">
  <div id="outside">
    <!-- prev/next links -->
    <div class="center">
      <span class="icon prev"></span>
      <span class="icon next"></span>
    </div>
    <!-- slideshow -->
    <div class="cycle-slideshow" 
      data-cycle-fx="scrollHorz"
      data-cycle-timeout="0"
      data-cycle-prev=".prev"
      data-cycle-next=".next"
      data-cycle-slides=">div"
      data-cycle-log="false"
      >
      <div class="slide-item slide1">
        <div class="title">
          <h1>Welcome to Starbis</h1>
        </div>
        <div class="body">
          <p>The smartest and most flexible Bootstrap template by TemplateMonster you've ever seen. Create exactly what you need with our powerful Bootstrap toolkit.</p>
        </div>
        <div class="cta-wrapper">
          <a class="btn trans" href="#">Default</a>
          <a class="btn default" href="#">Default</a>
        </div>
      </div>
      <div class="slide-item slide2">
        <div class="title">
          <h1>Unlimited Opportunities</h1>
        </div>
        <div class="body">
        <p>Starbis is the easiest way for you to build different sites without using many themes</p>
        </div>
        <div class="cta-wrapper">
          <a class="btn trans" href="#">Default</a>
          <a class="btn default" href="#">Default</a>
        </div>
      </div>
      <div class="slide-item slide3">
        <div class="title">
          <h1>Ultra Sharp & Responsive</h1>
        </div>
        <div class="body">
          <p>Beautiful and clean designs are optimized for all screen sizes and types. Taste a new meaning of Retina Ready.</p>
        </div>
        <div class="cta-wrapper">
          <a class="btn trans" href="#">Default</a>
          <a class="btn default" href="#">Default</a>
        </div>
      </div>
    </div>
  </div>
</div>
