
<div class="col-sm-6 col-md-4 col-lg-3">
  <div class="image-with-caption">
    <div class="image">
      <img src="images/1.jpg" alt="1" width="550" height="420" class="img-responsive">
    </div>
    <div class="caption">
      <p><strong>Starbis</strong></p>
    </div>
  </div>
</div>

<div class="col-sm-6 col-md-4 col-lg-3">
  <div class="image-with-caption">
    <div class="image">
      <img src="images/2.jpg" alt="1" width="550" height="420" class="img-responsive">
    </div>
    <div class="caption">
      <p>Tax <strong>Expert</strong></p>
    </div>
  </div>
</div>

<div class="col-sm-6 col-md-4 col-lg-3">
  <div class="image-with-caption">
    <div class="image">
      <img src="images/3.jpg" alt="1" width="550" height="420" class="img-responsive">
    </div>
    <div class="caption">
      <p>Law <strong>Expert</strong></p>
    </div>
  </div>
</div>

<div class="col-sm-6 col-md-4 col-lg-3">
  <div class="image-with-caption">
    <div class="image">
      <img src="images/4.jpg" alt="1" width="550" height="420" class="img-responsive">
    </div>
    <div class="caption">
      <p>All <strong>Risk</strong></p>
    </div>
  </div>
</div>

<div class="col-sm-6 col-md-4 col-lg-3">
  <div class="image-with-caption">
    <div class="image">
      <img src="images/5.jpg" alt="1" width="550" height="420" class="img-responsive">
    </div>
    <div class="caption">
      <p>Top <strong>Invest</strong></p>
    </div>
  </div>
</div>

<div class="col-sm-6 col-md-4 col-lg-3">
  <div class="image-with-caption">
    <div class="image">
      <img src="images/6.jpg" alt="1" width="550" height="420" class="img-responsive">
    </div>
    <div class="caption">
      <p>Easy <strong>Audit</strong></p>
    </div>
  </div>
</div>

<div class="col-sm-6 col-md-4 col-lg-3">
  <div class="image-with-caption">
    <div class="image">
      <img src="images/7.jpg" alt="1" width="550" height="420" class="img-responsive">
    </div>
    <div class="caption">
      <p>Fast <strong>Credit</strong></p>
    </div>
  </div>
</div>
