<div class="col-sm-6 col-md-4 col-lg-3">
  <div class="item">
    <div class="image">
      <img src="images/8.jpg" alt="1" width="550" height="420" class="img-responsive">
    </div>
    <div class="caption">
      <p>Blog <strong>Classic</strong></p>
    </div>
  </div>
</div>

<div class="col-sm-6 col-md-4 col-lg-3">
  <div class="item">
    <div class="image">
      <img src="images/9.jpg" alt="1" width="550" height="420" class="img-responsive">
    </div>
    <div class="caption">
      <p>Blog <strong>Grid</strong></p>
    </div>
  </div>
</div>

<div class="col-sm-6 col-md-4 col-lg-3">
  <div class="item">
    <div class="image">
      <img src="images/10.jpg" alt="1" width="550" height="420" class="img-responsive">
    </div>
    <div class="caption">
      <p>Blog <strong>Line</strong></p>
    </div>
  </div>
</div>

<div class="col-sm-6 col-md-4 col-lg-3">
  <div class="item">
    <div class="image">
      <img src="images/11.jpg" alt="1" width="550" height="420" class="img-responsive">
    </div>
    <div class="caption">
      <p>Blog <strong>Mansory</strong></p>
    </div>
  </div>
</div>

<div class="col-sm-6 col-md-4 col-lg-3">
  <div class="item">
    <div class="image">
      <img src="images/12.jpg" alt="1" width="550" height="420" class="img-responsive">
    </div>
    <div class="caption">
      <p>Blog <strong>Post</strong></p>
    </div>
  </div>
</div>
