<div class="row">
  <div class="col-md-3">
    <div class="item">
      <div class="image">
        <img src="images/13.jpg" alt="1" width="550" height="420" class="img-responsive">
      </div>
      <div class="caption">
        <p>Shop <strong>List</strong></p>
      </div>
    </div>
  </div>
  
  <div class="col-md-3">
    <div class="item">
      <div class="image">
        <img src="images/14.jpg" alt="1" width="550" height="420" class="img-responsive">
      </div>
      <div class="caption">
        <p>Shop <strong>Grid</strong></p>
      </div>
    </div>
  </div>

  <div class="col-md-3">
    <div class="item">
      <div class="image">
        <img src="images/15.jpg" alt="1" width="550" height="420" class="img-responsive">
      </div>
      <div class="caption">
        <p>Shop <strong>Product</strong></p>
      </div>
    </div>
  </div>

  <div class="col-md-3">
    <div class="item">
      <div class="image">
        <img src="images/16.jpg" alt="1" width="550" height="420" class="img-responsive">
      </div>
      <div class="caption">
        <p>Shop <strong>Cart</strong></p>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-3">
    <div class="item">
      <div class="image">
        <img src="images/17.jpg" alt="1" width="550" height="420" class="img-responsive">
      </div>
      <div class="caption">
        <p>Shop <strong>Checkout</strong></p>
      </div>
    </div>
  </div>
</div>
