<div class="row">
  <div class="col-md-3">
    <div class="item">
      <div class="image">
        <img src="images/18.jpg" alt="1" width="550" height="420" class="img-responsive">
      </div>
      <div class="caption">
        <p>Gallery <strong>Grid</strong></p>
      </div>
    </div>
  </div>

  <div class="col-md-3">
    <div class="item">
      <div class="image">
        <img src="images/19.jpg" alt="1" width="550" height="420" class="img-responsive">
      </div>
      <div class="caption">
        <p>Gallery <strong>Mansory</strong></p>
      </div>
    </div>
  </div>

  <div class="col-md-3">
    <div class="item">
      <div class="image">
        <img src="images/20.jpg" alt="1" width="550" height="420" class="img-responsive">
      </div>
      <div class="caption">
        <p>Gallery <strong>Cobbles</strong></p>
      </div>
    </div>
  </div>

  <div class="col-md-3">
    <div class="item">
      <div class="image">
        <img src="images/21.jpg" alt="1" width="550" height="420" class="img-responsive">
      </div>
      <div class="caption">
        <p>Gallery <strong>Item</strong></p>
      </div>
    </div>
  </div>
</div>
