<div class="row">
  <div class="col-md-3">
    <div class="item">
      <div class="image">
        <img src="images/22.jpg" alt="1" width="550" height="420" class="img-responsive">
      </div>
      <div class="caption">
        <p>About <strong>Us</strong></p>
      </div>
    </div>
  </div>
  
  <div class="col-md-3">
    <div class="item">
      <div class="image">
        <img src="images/23.jpg" alt="1" width="550" height="420" class="img-responsive">
      </div>
      <div class="caption">
        <p><strong>Services</strong></p>
      </div>
    </div>
  </div>

  <div class="col-md-3">
    <div class="item">
      <div class="image">
        <img src="images/24.jpg" alt="1" width="550" height="420" class="img-responsive">
      </div>
      <div class="caption">
        <p>Contact <strong>Us</strong></p>
      </div>
    </div>
  </div>

  <div class="col-md-3">
    <div class="item">
      <div class="image">
        <img src="images/25.jpg" alt="1" width="550" height="420" class="img-responsive">
      </div>
      <div class="caption">
        <p><strong>Appointment</strong></p>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-3">
    <div class="item">
      <div class="image">
        <img src="images/26.jpg" alt="1" width="550" height="420" class="img-responsive">
      </div>
      <div class="caption">
        <p><strong>Clients</strong></p>
      </div>
    </div>
  </div>
  
  <div class="col-md-3">
    <div class="item">
      <div class="image">
        <img src="images/27.jpg" alt="1" width="550" height="420" class="img-responsive">
      </div>
      <div class="caption">
        <p>Clients <strong>Testimonials</strong></p>
      </div>
    </div>
  </div>

  <div class="col-md-3">
    <div class="item">
      <div class="image">
        <img src="images/28.jpg" alt="1" width="550" height="420" class="img-responsive">
      </div>
      <div class="caption">
        <p>Our <strong>Team</strong></p>
      </div>
    </div>
  </div>

  <div class="col-md-3">
    <div class="item">
      <div class="image">
        <img src="images/29.jpg" alt="1" width="550" height="420" class="img-responsive">
      </div>
      <div class="caption">
        <p>Team member <strong>Profile</strong></p>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-3">
    <div class="item">
      <div class="image">
        <img src="images/30.jpg" alt="1" width="550" height="420" class="img-responsive">
      </div>
      <div class="caption">
        <p><strong>Careers</strong></p>
      </div>
    </div>
  </div>
  
  <div class="col-md-3">
    <div class="item">
      <div class="image">
        <img src="images/31.jpg" alt="1" width="550" height="420" class="img-responsive">
      </div>
      <div class="caption">
        <p><strong>Pricing</strong></p>
      </div>
    </div>
  </div>

  <div class="col-md-3">
    <div class="item">
      <div class="image">
        <img src="images/32.jpg" alt="1" width="550" height="420" class="img-responsive">
      </div>
      <div class="caption">
        <p><strong>FAQ</strong></p>
      </div>
    </div>
  </div>

  <div class="col-md-3">
    <div class="item">
      <div class="image">
        <img src="images/33.jpg" alt="1" width="550" height="420" class="img-responsive">
      </div>
      <div class="caption">
        <p>404 <strong>Page</strong></p>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-3">
    <div class="item">
      <div class="image">
        <img src="images/34.jpg" alt="1" width="550" height="420" class="img-responsive">
      </div>
      <div class="caption">
        <p>503 <strong>Page</strong></p>
      </div>
    </div>
  </div>
  
  <div class="col-md-3">
    <div class="item">
      <div class="image">
        <img src="images/35.jpg" alt="1" width="550" height="420" class="img-responsive">
      </div>
      <div class="caption">
        <p><strong>Maintenance</strong></p>
      </div>
    </div>
  </div>

  <div class="col-md-3">
    <div class="item">
      <div class="image">
        <img src="images/36.jpg" alt="1" width="550" height="420" class="img-responsive">
      </div>
      <div class="caption">
        <p>Coming <strong>Soon</strong></p>
      </div>
    </div>
  </div>

  <div class="col-md-3">
    <div class="item">
      <div class="image">
        <img src="images/37.jpg" alt="1" width="550" height="420" class="img-responsive">
      </div>
      <div class="caption">
        <p><strong>Login</strong></p>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-3">
    <div class="item">
      <div class="image">
        <img src="images/38.jpg" alt="1" width="550" height="420" class="img-responsive">
      </div>
      <div class="caption">
        <p><strong>Register</strong></p>
      </div>
    </div>
  </div>
  
  <div class="col-md-3">
    <div class="item">
      <div class="image">
        <img src="images/39.jpg" alt="1" width="550" height="420" class="img-responsive">
      </div>
      <div class="caption">
        <p>Search <strong>Results</strong></p>
      </div>
    </div>
  </div>

  <div class="col-md-3">
    <div class="item">
      <div class="image">
        <img src="images/40.jpg" alt="1" width="550" height="420" class="img-responsive">
      </div>
      <div class="caption">
        <p>Privacy <strong>Policy</strong></p>
      </div>
    </div>
  </div>

  <div class="col-md-3">
    <div class="item">
      <div class="image">
        <img src="images/41.jpg" alt="1" width="550" height="420" class="img-responsive">
      </div>
      <div class="caption">
        <p>Header <strong>Default</strong></p>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-3">
    <div class="item">
      <div class="image">
        <img src="images/42.jpg" alt="1" width="550" height="420" class="img-responsive">
      </div>
      <div class="caption">
        <p>Header <strong>Corporate Light</strong></p>
      </div>
    </div>
  </div>
  
  <div class="col-md-3">
    <div class="item">
      <div class="image">
        <img src="images/43.jpg" alt="1" width="550" height="420" class="img-responsive">
      </div>
      <div class="caption">
        <p>Header <strong>Corporate Dark</strong></p>
      </div>
    </div>
  </div>

  <div class="col-md-3">
    <div class="item">
      <div class="image">
        <img src="images/44.jpg" alt="1" width="550" height="420" class="img-responsive">
      </div>
      <div class="caption">
        <p>Footer <strong>Default</strong></p>
      </div>
    </div>
  </div>

  <div class="col-md-3">
    <div class="item">
      <div class="image">
        <img src="images/45.jpg" alt="1" width="550" height="420" class="img-responsive">
      </div>
      <div class="caption">
        <p>Footer <strong>Widget</strong></p>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-3">
    <div class="item">
      <div class="image">
        <img src="images/46.jpg" alt="1" width="550" height="420" class="img-responsive">
      </div>
      <div class="caption">
        <p>Footer <strong>Corporate</strong></p>
      </div>
    </div>
  </div>
</div>
