<div class="col-sm-6 col-md-4 col-lg-3">
  <div class="image-with-caption">
    <div class="image">
      <img src="images/47.jpg" alt="1" width="550" height="420" class="img-responsive">
    </div>
    <div class="caption">
      <p><strong>Accordion</strong></p>
    </div>
  </div>
</div>

<div class="col-sm-6 col-md-4 col-lg-3">
  <div class="image-with-caption">
    <div class="image">
      <img src="images/48.jpg" alt="1" width="550" height="420" class="img-responsive">
    </div>
    <div class="caption">
      <p><strong>Buttons</strong></p>
    </div>
  </div>
</div>

<div class="col-sm-6 col-md-4 col-lg-3">
  <div class="image-with-caption">
    <div class="image">
      <img src="images/49.jpg" alt="1" width="550" height="420" class="img-responsive">
    </div>
    <div class="caption">
      <p><strong>Grid</strong></p>
    </div>
  </div>
</div>

<div class="col-sm-6 col-md-4 col-lg-3">
  <div class="image-with-caption">
    <div class="image">
      <img src="images/50.jpg" alt="1" width="550" height="420" class="img-responsive">
    </div>
    <div class="caption">
      <p><strong>Forms</strong></p>
    </div>
  </div>
</div>

<div class="col-sm-6 col-md-4 col-lg-3">
  <div class="image-with-caption">
    <div class="image">
      <img src="images/51.jpg" alt="1" width="550" height="420" class="img-responsive">
    </div>
    <div class="caption">
      <p><strong>Icons</strong></p>
    </div>
  </div>
</div>

<div class="col-sm-6 col-md-4 col-lg-3">
  <div class="image-with-caption">
    <div class="image">
      <img src="images/52.jpg" alt="1" width="550" height="420" class="img-responsive">
    </div>
    <div class="caption">
      <p>Icon <strong>Lists</strong></p>
    </div>
  </div>
</div>

<div class="col-sm-6 col-md-4 col-lg-3">
  <div class="image-with-caption">
    <div class="image">
      <img src="images/53.jpg" alt="1" width="550" height="420" class="img-responsive">
    </div>
    <div class="caption">
      <p>Progress <strong>Bars</strong></p>
    </div>
  </div>
</div>

<div class="col-sm-6 col-md-4 col-lg-3">
  <div class="image-with-caption">
    <div class="image">
      <img src="images/54.jpg" alt="1" width="550" height="420" class="img-responsive">
    </div>
    <div class="caption">
      <p><strong>Tabs</strong></p>
    </div>
  </div>
</div>

<div class="col-sm-6 col-md-4 col-lg-3">
  <div class="image-with-caption">
    <div class="image">
      <img src="images/55.jpg" alt="1" width="550" height="420" class="img-responsive">
    </div>
    <div class="caption">
      <p>Table <strong>Styles</strong></p>
    </div>
  </div>
</div>

<div class="col-sm-6 col-md-4 col-lg-3">
  <div class="image-with-caption">
    <div class="image">
      <img src="images/56.jpg" alt="1" width="550" height="420" class="img-responsive">
    </div>
    <div class="caption">
      <p><strong>Typography</strong></p>
    </div>
  </div>
</div>
