<div id="starbis-block">
  <div class="container">
    <h2 class="title text-center">
      <span>What</span>
      <em>you get</em>
      <span>Whith Starbis</span>
    </h2>

    <div class="row">
      <div class="col-sm-6 col-md-4">
        <div class="item">
          <span class="icon line-square">&nbsp;</span>
          <h3 class="title">
            Advanced UI Kit
          </h3>
          <div class="line">&nbsp;</div>
          <div class="body">
            <p>Make the pages of your website look more attractive with our new Advanced UI Kit.</p>
          </div>
        </div>
      </div>

      <div class="col-sm-6 col-md-4">
        <div class="item">
          <span class="icon list">&nbsp;</span>
          <h3 class="title">
            Advanced UI Kit
          </h3>
          <div class="line">&nbsp;</div>
          <div class="body">
            <p>Intuitive and powerful Bootstrap toolkit offers align-items lgstomization possibilities.</p>
          </div>
        </div>
      </div>

      <div class="col-sm-6 col-md-4">
        <div class="item">
          <span class="icon history">&nbsp;</span>
          <h3 class="title">
            Advanced UI Kit
          </h3>
          <div class="line">&nbsp;</div>
          <div class="body">
            <p>Planning is the key to successfully and legally reducing your tax liability.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
