<div id="header-mobile" class="Fixed">
  <a href="#" id="menu-button">HOME</a>
  <p><?php print $title;?></p>
</div>

<div id="header">
  <div class="logo-wrapper">
    <!-- <img src="img/logo.png" class="logo"> -->
  </div>
  <nav id="my-menu">
    <ul class="">
      <li><a href="#">HOME</a></li>
      <li><a href="#">PAGES</a></li>
      <li><a href="#">PORTFOLIO</a></li>
      <li><a href="#">BLOG</a>
        <ul>
          <li><a href="#">Blog classic</a></li>
          <li><a href="#">Blog grid</a></li>
          <li><a href="#">Blog line</a></li>
          <li><a href="#">Blog masonry</a></li>
          <li><a href="#">Blog post</a></li>
        </ul>
      </li>
      <li><a href="#">SHOP</a></li>
      <li><a href="#">COMPONENTS</a></li>
    </ul>
  </nav>
</div>

<div id="header-desktop">
  <div class="container">
    <div class="row">
      <div class="col-xs-6">
        <div class="logo">
          <img src="images/logo-black.svg" class="img-responsive">
        </div>
      </div>
      <div class="col-xs-1">
        <a href="#" class="home">HOME</a>
      </div>
      <div class="col-xs-1">
        <a href="#" class="about">ABOUT</a>
      </div>
      <div class="col-xs-1">
        <a href="#" class="services">SERVICES</a>
      </div>
      <div class="col-xs-1">
        <a href="#" class="news">NEWS</a>
      </div>
      <div class="col-xs-1">
        <a href="#" class="gallery">GALLERY</a>
      </div>
      <div class="col-xs-1">
        <a href="#" class="contacts">CONTACTS</a>
      </div>
    </div>
  </div>
</div>
