<div id="header-mobile" class="Fixed">
  <a href="#" id="menu-button"></a>
  <img src="images/logo-black.svg" class="logo">
</div>

<div id="header">
  <nav id="my-menu">
    <ul class="">
      <li><a href="#">HOME</a></li>
      <li><a href="#">PAGES</a></li>
      <li><a href="#">PORTFOLIO</a></li>
      <li><a href="#">BLOG</a>
        <ul>
          <li><a href="#">Blog classic</a></li>
          <li><a href="#">Blog grid</a></li>
          <li><a href="#">Blog line</a></li>
          <li><a href="#">Blog masonry</a></li>
          <li><a href="#">Blog post</a></li>
        </ul>
      </li>
      <li><a href="#">SHOP</a></li>
      <li><a href="#">COMPONENTS</a></li>
    </ul>
  </nav>
</div>

<nav id="header-desktop" class="navbar navbar-fixed-top">
  <div class="container">
    <div class="logo navbar-header">
      <img src="images/logo-black.svg" class="navbar-brand img-responsive">
    </div>
      <ul class="nav navbar-nav">
        <li><a href="#">HOME</a></li>
        <li><a href="#">PAGES</a></li>
        <li><a href="#">PORTFOLIO</a></li>
        <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">BLOG</a>
          <ul class="dropdown-menu">
            <li><a href="#">Blog classic</a></li>
            <li><a href="#">Blog grid</a></li>
            <li><a href="#">Blog line</a></li>
            <li><a href="#">Blog masonry</a></li>
            <li><a href="#">Blog post</a></li>
          </ul>
        </li>
      <li><a href="#">SHOP</a></li>
      <li><a href="#">COMPONENT</a></li>
    </ul>
    <div class="input-group">
      <input type="text" class="form-control" placeholder="Search">
      <div class="input-group-btn">
        <button class="btn btn-default" type="submit">
          <i class="glyphicon glyphicon-search"></i>
        </button>
      </div>
      </div>
  </div>
</nav>
