<div id="header-mobile" class="Fixed">
  <a href="#" id="menu-button"></a>
  <img src="images/logo-black.svg" class="logo">
</div>

<div id="header">
  <nav id="my-menu">
    <ul class="">
      <li><a href="#">HOME</a></li>
      <li><a href="#">PAGES</a></li>
      <li><a href="#">PORTFOLIO</a></li>
      <li><a href="#">BLOG</a>
        <ul>
          <li><a href="#">Blog classic</a></li>
          <li><a href="#">Blog grid</a></li>
          <li><a href="#">Blog line</a></li>
          <li><a href="#">Blog masonry</a></li>
          <li><a href="#">Blog post</a></li>
        </ul>
      </li>
      <li><a href="#">SHOP</a></li>
      <li><a href="#">COMPONENTS</a></li>
    </ul>
  </nav>
</div>

<div id="header-desktop">
  <div class="container">
    <div class="row">
      <div class="col-xs-6">
        <div class="logo">
          <img src="images/logo-black.svg" class="img-responsive">
        </div>
      </div>
      <nav>
        <ul>
          <li><a href="#">HOME</a></li>
          <li><a href="#">PAGES</a></li>
          <li><a href="#">PORTFOLIO</a></li>
          <li><a href="#">BLOG</a>
            <ul>
              <li><a href="#">Blog classic</a></li>
              <li><a href="#">Blog grid</a></li>
              <li><a href="#">Blog line</a></li>
              <li><a href="#">Blog masonry</a></li>
              <li><a href="#">Blog post</a></li>
            </ul>
          </li>
        <li><a href="#">SHOP</a></li>
        <li><a href="#">COMPONENT</a></li>
      </ul>
      </nav>
      </div>
    </div>
  </div>
</div>
