<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">

<meta name="description" content="">
<meta name="author" content="">
<link rel="icon" href="<?php echo $level . 'favicon.png'; ?>">

<!-- Bootstrap core CSS -->
<link href="<?php echo $level . 'bootstrap/dist/css/bootstrap.min.css'; ?>" rel="stylesheet">

<!-- mmenu core CSS -->
<link rel="stylesheet" type="text/css" href="<?php echo $level . 'css/mmenu.min.css'; ?>" />

<!-- Global Styles from D4ALL CSS -->
<link href="<?php echo $level . 'css/styles.css'; ?>" rel="stylesheet">

<!-- jQuery JS -->
<script src="<?php echo $level . 'js/jquery.min.js'; ?>"></script>

<!-- Bootstrap core JS -->
<script src="<?php echo $level . 'bootstrap/dist/js/bootstrap.min.js'; ?>"></script>

<!-- mmenu library -->
<script src="<?php echo $level . 'js/mmenu/jquery.mmenu.min.js'; ?>"></script>
<script src="<?php echo $level . 'js/mmenu/jquery.mmenu.fixedelements.min.js'; ?>"></script>

<!-- Cycle2 JS library -->
<script src="<?php echo $level . 'js/cycle2/jquery.cycle2.min.js'; ?>"></script>
<script src="<?php echo $level . 'js/cycle2/jquery.cycle2.carousel.min.js'; ?>"></script>

<!-- Global Scripts from D4ALL JS -->
<script src="<?php echo $level . 'js/scripts.js'; ?>"></script>

<!-- Hero Slider from D4ALL JS -->
<script src="<?php echo $level . 'js/hero.slider.js'; ?>"></script>

<!-- Hero Tabs Block from D4ALL JS -->
<script src="<?php echo $level . 'js/tabs.block.js'; ?>"></script>

<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
