<div id="blog-2">
  <div class="container">
    <div class="row">
      <div class="col-xs-2 text-center profile">
        <img src="../images/blog-joan.png" class="img-responsive" alt="">
        <p>Joan Williams</p>
      </div>
      <div class="col-xs-10 public">
        <h3>5 Simple Steps to Blog's Success</h3>
        <p>
          Unfortunately people will not come to your blog just to see what you have published on it. To make sure that your blog becomes a successful one, you have to work on it to attract visitors interested in your content.
          This can be achieved by serious work on some important aspects. In a word, give people the reason to see what you have to say or offer.
        </p>
        <div class="details">
          <ul>
            <li>05/14/2016</li>
            <li><a href="">Bussiness</a>,<a href="">Blog</a></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-2 text-center profile">
        <img src="../images/blog-tom.png" class="img-responsive" alt="">
        <p>Tom Park</p>
      </div>
      <div class="col-xs-10 public">
        <h3>Making Money Online with Your Computer Only</h3>
        <p>
          Making money online is a kind of everyone’s dream job. No investments are needed and you can do whatever you need to do when you are in the mood or have free time.Flexible work schedule is something you’ll hardly get working at the office. However, online business rarely starts to bring you money from the very first day. It takes some time as a rule. But once you understand the whole process (like what are your abilities, where to work, for whom to work and so on) you'll be earning money in no time.
        </p>
        <div class="details">
          <ul>
            <li>05/17/2016</li>
            <li><a href="">Bussiness</a>,<a href="">Startup</a></li>
          </ul>
        </div>
      </div>
    </div>
    <iframe width="100%" height="auto" src="https://www.youtube.com/embed/VrLSBsOkP6k" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    <div class="row">
      <div class="col-xs-2 text-center profile">
        <img src="../images/blog-jhon.png" class="img-responsive" alt="">
        <p>Jhon Miller</p>
      </div>
      <div class="col-xs-10 public">
        <h3>How to Create Perfect Color Combinations</h3>
        <p>
          One of the most challenging and tricky parts of the design process can be choosing a color palette that represents your brand or message, while creating an amazing base for the design.
          Creating perfect color combinations is more than just picking two colors and running with it. There’s actually quite a bit of science and design color theory behind it. Today, we’ll look at nine ways to help you create a more perfect color palette.
        </p>
        <div class="details">
          <ul>
            <li>04/10/2016</li>
            <li><a href="">Design</a>,<a href="">Color</a></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-2 text-center profile">
        <img src="../images/blog-julien.png" class="img-responsive" alt="">
        <p>Julien Miro</p>
      </div>
      <div class="col-xs-10 public">
        <h3>10 Type Rules for an Excellent User Experience</h3>
        <p>
          When it comes to websites and apps, good typography is more than just a pretty typeface. Letting has to be highly readable – and scannable – while providing a solid visual connection to the content.
          It’s a pretty tall order, but something most designers can do with a little practice.
          Today, we’re going to look at 10 “rules” you can follow to help create an awesome typographic user experience.
        </p>
        <div class="details">
          <ul>
            <li>04/3/2016</li>
            <li><a href="">Type</a><a href="">Tips</a></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="row text-center">
      <ul class="pagination">
        <li><a href="">&laquo;</a></li>
        <li><a href="">1</a></li>
        <li><a href="">2</a></li>
        <li><a href="">3</a></li>
        <li><a href="">&raquo;</a></li>
      </ul>
    </div>
  </div>
</div>
